### ISSUE TITLE
Contract Details Page

### ISSUE THREAD

**Issue by ckoopmann** [MoneyLSP/avow#11]
Once the User has selected a Contract in the UI he should see a page displaying relevant details about the contract such as:
- Collateral
- Minted Tokens
- Long / Short Token Addresses (+name / symbol)
- Expiration Time
- Price Feed
- Financial Library / Type (Linear CFD, Covered Call, Range Loan etc)
- Financial Library Parameters (strike price, upper / lower bound)

**Comment by ElmoArmy** [comment]
- [ ] Collateral
- [ ] Minted Tokens
- [ ] Long / Short Token Addresses (+name / symbol)
- [ ] Expiration Time
- [ ] Price Feed
- [ ] Financial Library / Type
- [ ] Financial Library Parameters (strike price, upper / lower bound)
