### ISSUE TITLE
Enable wallet connection in the UI

### ISSUE THREAD

**Issue by ckoopmann** [MoneyLSP/avow#9]
The user needs to be able to connect his wallet to the Dapp which we then use as web3 / ethers provider:

- At least Metamask needs to be supported Ideally also other Providers (like WalletConnect)
- User needs to be able to connect / disconnect by clicking a button in the UI.
- The Application needs to detect changes in Network / Account and react / update accordingly.
- When the user hasn't connected maybe we should show a message telling him to connect to press the connect button if he wants to use the app.

**Comment by ElmoArmy** [comment]
- [x] At least Metamask needs to be supported Ideally also other Providers (like WalletConnect)

- [x] User needs to be able to connect / disconnect by clicking a button in the UI.

- [ ] The Application needs to detect changes in Network / Account and react / update accordingly.

**I'd like to understand what you think should happen on Network change. I figure we can track a state variable in Web3 for the selected account though so thats easy enough.**

- [ ]  When the user hasn't connected maybe we should show a message telling him to connect to press the connect button if he wants to use the app.

**How do you figure we handle this? Since this is not a purely technical question, maybe I'll ask the other guys what would make sense to them, but I'd love to hear your opinion.**

**Comment by ckoopmann** [comment]
> I'd like to understand what you think should happen on Network change. I figure we can track a state variable in the Web3 module for the selected account though so thats easy enough.

Since we are only deploying on kovan I think for now the app should just show a message that the user is on the "wrong" network if he is not logged into kovan while showing a successfull connection banner when he is connected to kovan.

**Comment by ckoopmann** [comment]
> How do you figure we handle this? Since this is not a purely technical question, maybe I'll ask the other guys what would make sense to them, but I'd love to hear your opinion.

I would just show a banner similarily to how I did it it here. But I am not very particular about the design, if we can come up with a different design that makes the "issue" clearly visible to the user without being too ugly then thats fine with me:
https://block-paper-scissors.com/#/

**Comment by ckoopmann** [comment]
Again I don't think we should spend too much time on the design issues for that.
You are free to copy / adapt what I did in my previous app.

We could also follow alternative approaches such as encoding all of this information into the display of the connect button. Maybe highlighting it in different ways etc. depending on wether the user is "successfully" (e.g. on the right network) connected to the app.

I would just go with whatever is easiest for now, as long as it still conveys the relevant information.

**Comment by ckoopmann** [comment]
Obviously when the network / account changes all other data in the app that is account / network specific (like Token Balences) needs to update automatically.

Although this is something we will tackle when we actuallly implement the display of this information we should keep this in mind while developing the web3 connection. E.g. add some simple event listeners for these changes that we can easily extend later to add additional vuex actions / mutations (such as "update" token balances).

**Comment by ElmoArmy** [comment]
> Obviously when the network / account changes all other data in the app that is account / network specific (like Token Balences) needs to update automatically.
> 
> 
> 
> Although this is something we will tackle when we actuallly implement the display of this information we should keep this in mind while developing the web3-module. E.g. add some simple event listeners now for account / network change that we can easily extend later to add additional vuex actions / mutations (such as "update" token balances).

I say for MVP let's do a reload of the app and for MVP v2 we work on auto magically requesting new data. My rationale being when we record the demo video, we will know to be on a appropriate test network.

**Comment by ElmoArmy** [comment]
#32 Handles the network reload.
